/* Generated by tools/png2ds.py -- do not edit by hand. */
#ifndef GFX_DATA_H
#define GFX_DATA_H

#define N_GAME_TILES   24 /* per tileset */
#define MENU_TILE_BASE 96  /* hw tile index of menu tile 0 */
#define N_BG_HW_TILES  101
#define HERO_FRAMES    8   /* frame = dir*2 + step; dirs D,L,U,R */
#define FRAME16_BYTES  256 /* one 16x16 8bpp frame */
#define FRAME64_BYTES  4096
#define N_MENU4_TILES  6 /* 0=blank,1=corner,2=vedge,3=hedge,4=fill,5=cursor */

#define N_TITLE_TILES  70
extern const unsigned short enemyGfx_slime[2048];
extern const unsigned short enemyGfx_troll[2048];
extern const unsigned short bossGfx_grak[128];
extern const unsigned short npcSprite_NPC2[128];
#define BACKDROP_HW_TILES 384 /* 24x16, row-major */
extern const unsigned short tilesetGfx_default[3072];
extern const unsigned short tilesetGfx_testset[3072];
extern const unsigned short backdropGfx_plains[12288];
extern const unsigned short bgPal[256];
extern const unsigned short objPal[256];
extern const unsigned short titlePal[256];
extern const unsigned short titleTiles[2240];
extern const unsigned short titleMap[768];
extern const unsigned short menuTiles8Data[160];
extern const unsigned short heroGfxData[1024];
extern const unsigned short mageGfxData[1024];
extern const unsigned short npcGfxData[128];
extern const unsigned short menuTiles4Data[96];
extern const unsigned short menuPal16[16];

#endif
