/* Generated by tools/gen_maps.py -- do not edit by hand. */
#ifndef MAP_IDS_H
#define MAP_IDS_H

enum {
	MAP_OVERWORLD = 0,
	MAP_TOWN_WEST,
	MAP_TOWN_EAST,
	MAP_WH_HOUSE1,
	MAP_TILE_TEST,
	N_MAPS,
};

enum {
	TILESET_DEFAULT = 0,
	TILESET_TESTSET,
	N_TILESETS,
};

#define START_MAP MAP_TOWN_WEST
#define START_X   9
#define START_Y   13
#define DEATH_MAP MAP_TOWN_WEST
#define DEATH_X   9
#define DEATH_Y   13

#endif
