/* Generated by tools/gen_scripts.py -- do not edit by hand. */
#ifndef SCRIPTS_DATA_H
#define SCRIPTS_DATA_H

#define SCRIPT_COUNT 2

extern const unsigned char  scriptData[60];
extern const unsigned short scriptOffset[2];
extern const char scriptText[200];

#endif
