/* Generated by tools/gen_scripts.py -- do not edit by hand. */
#ifndef SCRIPTS_DATA_H
#define SCRIPTS_DATA_H

#define SCRIPT_COUNT 3

extern const unsigned char  scriptData[71];
extern const unsigned short scriptOffset[3];
extern const char scriptText[215];

#endif
