#!/usr/bin/env python3
"""
gen_scripts.py -- compile every map event script in data/maps.json
into source/scripts_data.c + include/scripts_data.h. Run from the
project root, AFTER gen_db and BEFORE gen_maps:

	gen_db -> png2ds -> gen_scripts -> gen_maps

gen_maps imports script_index() from here so the event tables it
emits into maps.c agree with the bytecode layout.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import script_lang
from script_lang import ScriptError

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MAX_EVENTS = 8                   # per map; keep in sync with maps.h
TRIGGER_KINDS = ("on_load", "on_flag", "on_tile")


def fail(msg):
	sys.exit("gen_scripts: " + msg)


def events_of(m):
	return m.get("events", [])


def check_trigger(mname, i, ev, m, flags):
	t = ev.get("trigger") or {}
	kind = t.get("kind")
	if kind not in TRIGGER_KINDS:
		fail("%s event %d: bad trigger kind %r (one of %s)"
		     % (mname, i, kind, "/".join(TRIGGER_KINDS)))
	if kind == "on_flag":
		if not t.get("flag"):
			fail("%s event %d: on_flag needs a flag" % (mname, i))
	if kind == "on_tile":
		x, y = t.get("x"), t.get("y")
		if not (isinstance(x, int) and isinstance(y, int)
		        and 0 <= x < m["w"] and 0 <= y < m["h"]):
			fail("%s event %d: on_tile (%r,%r) outside %dx%d map"
			     % (mname, i, x, y, m["w"], m["h"]))
	fl = t.get("flag")
	if fl and flags is not None and fl not in flags:
		fail("%s event %d: unknown flag %r" % (mname, i, fl))


def validate(mapsdata, db):
	"""Parse + resolve every event script; check triggers. Called by
	the editor's save_all and by generate()."""
	refs = script_lang.Refs.from_data(db, mapsdata)
	flags = set(db.get("flags", []))
	for m in mapsdata["maps"]:
		evs = events_of(m)
		if len(evs) > MAX_EVENTS:
			fail("%s: more than %d events" % (m["cid"], MAX_EVENTS))
		for i, ev in enumerate(evs):
			check_trigger(m["cid"], i, ev, m, flags)
			try:
				script_lang.validate_script(ev.get("script", ""), refs)
			except ScriptError as e:
				fail("%s event %d: %s" % (m["cid"], i, e))


def script_index(mapsdata):
	"""Deterministic event -> script index mapping shared with
	gen_maps: {(map_ordinal, event_ordinal): script_index}."""
	out = {}
	n = 0
	for mi, m in enumerate(mapsdata["maps"]):
		for ei in range(len(events_of(m))):
			out[(mi, ei)] = n
			n += 1
	return out


def _c_bytes(name, data):
	out = ["const unsigned char %s[%d] = {" % (name, max(1, len(data)))]
	if not data:
		out.append("\t0,")
	for i in range(0, len(data), 12):
		out.append("\t" + ", ".join("0x%02X" % b
		                            for b in data[i:i + 12]) + ",")
	out.append("};")
	return out


def _c_text(name, blob):
	"""Text pool as a char array (NUL separated payloads)."""
	out = ["const char %s[%d] = {" % (name, max(1, len(blob)))]
	if not blob:
		out.append("\t0,")
	for i in range(0, len(blob), 12):
		out.append("\t" + ", ".join(str(b) for b in blob[i:i + 12])
		           + ",")
	out.append("};")
	return out


def generate(mapsdata, db, root=ROOT):
	validate(mapsdata, db)
	refs = script_lang.Refs.from_data(db, mapsdata)

	text = bytearray()               # global NUL-separated text pool
	pool = {}                        # payload -> offset (dedup)

	def addstr(payload):
		if payload not in pool:
			off = len(text)
			if off + len(payload) + 1 > 0xFFFF:
				fail("script text exceeds 65535 bytes")
			pool[payload] = off
			text.extend(payload.encode("ascii", "replace"))
			text.append(0)
		return pool[payload]

	blobs = []
	names = []
	for m in mapsdata["maps"]:
		for i, ev in enumerate(events_of(m)):
			ast = script_lang.parse(ev.get("script", ""))
			try:
				blob = script_lang.compile_script(ast, refs, addstr)
			except ScriptError as e:
				fail("%s event %d: %s" % (m["cid"], i, e))
			blobs.append(blob)
			names.append("%s event %d" % (m["cid"], i))

	offsets, data = [], bytearray()
	for b in blobs:
		offsets.append(len(data))
		data.extend(b)
	if len(data) > 0xFFFF:
		fail("script bytecode exceeds 65535 bytes")

	count = len(blobs)
	c = ["/* Generated by tools/gen_scripts.py -- do not edit by "
	     "hand. */", '#include "scripts_data.h"', ""]
	c += _c_bytes("scriptData", bytes(data))
	c.append("")
	# empty-symbol rule: keep tables linkable with zero scripts
	c.append("const unsigned short scriptOffset[%d] = { %s };"
	         % (max(1, count),
	            ", ".join(str(o) for o in offsets) if offsets else "0"))
	c.append("")
	c += _c_text("scriptText", bytes(text))
	c.append("")

	h = ["/* Generated by tools/gen_scripts.py -- do not edit by "
	     "hand. */",
	     "#ifndef SCRIPTS_DATA_H", "#define SCRIPTS_DATA_H", "",
	     "#define SCRIPT_COUNT %d" % count,
	     "",
	     "extern const unsigned char  scriptData[%d];"
	     % max(1, len(data)),
	     "extern const unsigned short scriptOffset[%d];"
	     % max(1, count),
	     "extern const char scriptText[%d];" % max(1, len(text)),
	     "", "#endif", ""]

	with open(os.path.join(root, "source", "scripts_data.c"),
	          "w") as f:
		f.write("\n".join(c) + "\n")
	with open(os.path.join(root, "include", "scripts_data.h"),
	          "w") as f:
		f.write("\n".join(h))
	return ("%d scripts, %d bytecode bytes, %d text bytes"
	        % (count, len(data), len(text)))


def main():
	mapsdata = json.load(open(os.path.join(ROOT, "data",
	                                       "maps.json")))
	db = json.load(open(os.path.join(ROOT, "data", "database.json")))
	print("gen_scripts:", generate(mapsdata, db))


if __name__ == "__main__":
	main()
