/* Generated by tools/gen_db.py -- do not edit by hand. */
#include "db_data.h"
#include "soundbank.h"

extern const unsigned short enemyGfx_slime[];
extern const unsigned short enemyGfx_troll[];

const EnemyDef enemyDefs[N_ENEMIES] = {
	{ "Slime", enemyGfx_slime, 8, 6, 4, 4, 2, 3 },
	{ "Troll", enemyGfx_troll, 20, 12, 8, 5, 8, 12 },
};

const TroopDef troopDefs[N_TROOPS] = {
	{ "a Slime", 1, { 0, 0, 0 } },
	{ "two Slimes", 2, { 0, 0, 0 } },
	{ "a Troll", 1, { 1, 0, 0 } },
	{ "a Slime and a Troll", 2, { 0, 1, 0 } },
	{ "two Trolls", 2, { 1, 1, 0 } },
};

const ItemDef itemDefs[N_ITEMS] = {
	{ "Herb", 10, 10 },
	{ "Supherb", 10, 20 },
};

const SpellDef spellDefs[6] = {
	{ "Heal", 4, 1, SPELL_HEAL, 10, false },
	{ "Fire", 3, 2, SPELL_FIRE, 8, false },
	{ "Healmore", 8, 5, SPELL_HEAL, 30, false },
	{ "Firebolt", 6, 6, SPELL_FIRE, 18, false },
	{ "Healall", 12, 8, SPELL_HEAL, 20, true },
	{ "Firestorm", 10, 9, SPELL_FIRE, 14, true },
};

extern const unsigned short bossGfx_grak[];
const BossDef bossDefs[1] = {
	{ bossGfx_grak, TROOP_TROLL_PAIR, -1 },
};

const PlayerDef playerDefs[PARTY_SIZE] = {
	{ "HERO", 24, 0, 10, 8, 6, 6, 0, 2, 1, 1, 0, { 0 } },
	{ "MAGE", 16, 8, 6, 5, 8, 4, 3, 1, 1, 2, 6, { 0, 1, 2, 3, 4, 5 } },
};

const int expNeed[MAX_LEVEL + 1] = { 0, 0, 7, 23, 47, 90, 160, 270, 430, 660, 990 };

const unsigned char startItems[N_ITEMS] = { 2, 0 };

const int titleMusic = -1;
const int battleMusic = MOD_MBAT;
const int victoryMusic = MOD_FANFARE;
